const JSP1_CONTENT = {
  "INC-A1": {
    theme: "Les EPI",
    method: "",
    important: [],
    book: "106-121",
  },
  "INC-A2": {
    theme: "La protection respiratoire",
    method: "Théorique",
    important: [
      "La pression à l’intérieur de la pièce faciale: 1,5 à 3 mbar au dessus de la pression atmosphérique (soit 1,0015 à 1.003 bar environ)",
    ],
    book: "122-125",
  },
  "INC-B1": {
    theme: "Le lot de sauvetage et de protection contre les chutes",
    method: "",
    important: ["La sécurité ! Un mousqueton ne s’utilise jamais ouvert"],
    book: "127-133",
  },
  "INC-B2": {
    theme: "Les échelles à main",
    method: "",
    important: [
      "Le pied d’échelle",
      "Quelles étapes de la MGO faire avec une échelle",
    ],
    book: "134-137",
  },
  "INC-C1": {
    theme: "Les matériels de lutte contre l'incendie",
    method: "",
    important: [
      "Le bon sens (on établit pas une ligne sur une ligne de chemin de fer …)",
    ],
    book: "139-155",
  },
  "INC-C2": {
    theme: "Les principes de la défense extérieure contre l'incendie",
    method: "",
    important: [],
    book: "156-160",
  },
  "INC-C3": {
    theme: "La marche générale des opérations de lutte contre l'incendie",
    method: "",
    important: [],
    book: "161-170",
  },
  "SC-A1": {
    theme: "Les valeurs et l'éthique JSP",
    method: "",
    important: ["Le savoir-être qui n'est pas réservé au centre de secours"],
    book: "172",
  },
  "SC-A2": {
    theme: "Le réseau associatif fédéral",
    method: "",
    important: [],
    book: "173-174",
  },
  "SC-A3": {
    theme: "Le rôle du réseau associatif et ses valeurs",
    method: "",
    important: [],
    book: "174",
  },
  "SC-A4": {
    theme: "L'engagement citoyen",
    method: "",
    important: [],
    book: "175-180",
  },
  "SC-A5": {
    theme: "Les protocoles et cérémonies",
    method: "",
    important: [],
    book: "181-186",
  },
  "SC-B1": {
    theme: "Information préventive aux comportements qui sauvent",
    method: "",
    important: [],
    book: "188-189",
  },
  "SC-C1": {
    theme: "Les grades",
    method: "",
    important: [
      "Les personnels du SDIS: le DDSIS, les chefs de centre et le chef d’unité opérationnelle de l’agglo",
      "Officiers: Un Ltn = 2 à 4 engins. ",
      "Un Cne = 2 à 4 lieutenants, etc.",
    ],
    book: "191-194",
  },
  "APS-A1": {
    theme: "La préparation physique",
    method: "",
    important: [],
    book: "196-201",
  },
  "APS-A2": {
    theme: "Les objectifs de l'activité physique chez les sapeurs-pompiers",
    method: "",
    important: [],
    book: "202-203",
  },
  M: {
    theme: "Manœuvres",
    method: "",
    important: [],
    book: "",
  },
};
const JSP2_CONTENT = {
  "PS-A1": {
    theme: "Protection et prise en charge d'une détresse vitale",
    method: "",
    important: [],
    book: "5-86",
  },
  "INC-A1": {
    theme:
      "Les contraintes liées à l'utilisation d'un appareil respiratoire isolant et la préparation à l'engagement",
    method: "",
    important: [],
    book: "88-96",
  },
  "INC-B1": {
    theme: "Le lot de sauvetage et de protection contre les chutes",
    method: "",
    important: [],
    book: "98-113",
  },
  "INC-B2": {
    theme: "Les échelles à coulisse",
    method: "",
    important: [],
    book: "114-118",
  },
  "INC-C1": {
    theme: "La combustion",
    method: "",
    important: [],
    book: "120",
  },
  "INC-C2": {
    theme: "Les modes de propagation",
    method: "",
    important: [],
    book: "121",
  },
  "INC-C3": {
    theme: "Le comportement et la réaction au feu des matériaux",
    method: "",
    important: [],
    book: "122-124",
  },
  "INC-C4": {
    theme: "Les classes de feux et les différents agents extincteurs",
    method: "",
    important: [],
    book: "125",
  },
  "INC-C5": {
    theme: "Les procédés d'extinction",
    method: "",
    important: [],
    book: "126",
  },
  "INC-C6": {
    theme: "Les établissements",
    method: "",
    important: [],
    book: "127-137",
  },
  "PPBE-A1": {
    theme: "Les matériels d'épuisement et d'assèchement",
    method: "",
    important: [],
    book: "139-142",
  },
  "PPBE-A2": {
    theme: "Les matériels électriques et d'éclairage",
    method: "",
    important: [],
    book: "143-145",
  },
  "SC-A1": {
    theme:
      "Les risques d'incendie et les risques liés aux accidents de la vie courante",
    method: "",
    important: [],
    book: "147-159",
  },
  "SC-B1": {
    theme: "Les statuts des sapeurs-pompiers",
    method: "",
    important: [],
    book: "161",
  },
  "SC-B2": {
    theme: "Les engins d'incendie et de secours",
    method: "",
    important: [],
    book: "163-166",
  },
  "APS-A1": {
    theme: "La préparation physique",
    method: "",
    important: [],
    book: "168-173",
  },
  M: {
    theme: "Manœuvres",
    method: "",
    important: [],
    book: "",
  },
};
const JSP3_CONTENT = {
  "PS-A1": {
    theme: "Les bilans, détresses vitales et autres atteintes",
    method: "",
    important: [],
    book: "6-96",
  },
  "INC-A1": {
    theme: "L'explosimétrie et la coupure des fluides",
    method: "",
    important: [],
    book: "98-108",
  },
  "INC-A2": {
    theme: "L'engagement sous ARI",
    method: "",
    important: [],
    book: "109-121",
  },
  "INC-A3": {
    theme: "Les systèmes d'information et de communication",
    method: "",
    important: [],
    book: "122-130",
  },
  "INC-B1": {
    theme: "Le lot de sauvetage et de protection contre les chutes",
    method: "",
    important: [],
    book: "132-139",
  },
  "INC-B2": {
    theme: "L'échelle à crochets",
    method: "",
    important: [],
    book: "140",
  },
  "INC-C1": {
    theme: "Notions élémentaires d'hydraulique",
    method: "",
    important: [],
    book: "143",
  },
  "INC-C2": {
    theme: "Les points d'eau incendie",
    method: "",
    important: [],
    book: "144-148",
  },
  "INC-C3": {
    theme: "Les établissements",
    method: "",
    important: [],
    book: "149-155",
  },
  "INC-C4": {
    theme: "Les moyens facilitant l'action des secours",
    method: "",
    important: [],
    book: "156-164",
  },
  "PPBE-A1": {
    theme: "Matériels d'épuisement et d'assèchement",
    method: "",
    important: [],
    book: "165-167",
  },
  "SC-A1": {
    theme: "Les risques majeurs et l'information de la population",
    method: "",
    important: [],
    book: "169-190",
  },
  "SC-B1": {
    theme: "L'organisation et les missions du SIS",
    method: "",
    important: [],
    book: "192-195",
  },
  "APS-A1": {
    theme: "La préparation physique",
    method: "",
    important: [],
    book: "197-202",
  },
  "APS-A2": {
    theme: "L'hygiène de vie",
    method: "",
    important: [],
    book: "203-204",
  },
  M: {
    theme: "Manœuvres",
    method: "",
    important: [],
    book: "",
  },
};
const JSP4_CONTENT = {
  "PS-A1": {
    theme: "Prompt secours",
    method: "",
    important: [],
    book: "",
  },
  "INC-A1": {
    theme: "Rôle de l'équipier au sein du binôme de reconnaissance",
    method: "",
    important: [],
    book: "",
  },
  "INC-A2": {
    theme: "Les différents types de risques et actions adaptées",
    method: "",
    important: [],
    book: "",
  },
  "INC-A3": {
    theme: "Préservation des traces et indices",
    method: "",
    important: [],
    book: "",
  },
  "INC-A4": {
    theme: "Notions de prévention appliquées à l'opération",
    method: "",
    important: [],
    book: "",
  },
  "INC-A5": {
    theme: "Mise en œuvre de l'ARI",
    method: "",
    important: [],
    book: "",
  },
  "INC-B1": {
    theme: "Les techniques de sauvetages et de mises en sécurité",
    method: "",
    important: [],
    book: "",
  },
  "INC-B2": {
    theme: "Les techniques de sauvetage de sauveteur",
    method: "",
    important: [],
    book: "",
  },
  "INC-C1": {
    theme: "Les phénomènes thermiques et les techniques d'intervention",
    method: "",
    important: [],
    book: "",
  },
  "INC-C2": {
    theme: "L'utilisation des lances",
    method: "",
    important: [],
    book: "",
  },
  "INC-C3": {
    theme: "Établissements spécifiques",
    method: "",
    important: [],
    book: "",
  },
  "INC-C4": {
    theme: "Techniques d'autoprotection",
    method: "",
    important: [],
    book: "",
  },
  "PPBE-A1": {
    theme: "Le matériel de protection des biens",
    method: "",
    important: [],
    book: "",
  },
  "PPBE-A2": {
    theme: "Intervention sur les ascenseurs",
    method: "",
    important: [],
    book: "",
  },
  "PPBE-B1": {
    theme: "La capture d'animaux",
    method: "",
    important: [],
    book: "",
  },
  "PPBE-B2": {
    theme: "La neutralisation d'hyménoptères",
    method: "",
    important: [],
    book: "",
  },
  "SC-A1": {
    theme: "Les valeurs et l'éthique des sapeurs-pompiers",
    method: "",
    important: [],
    book: "",
  },
  "SC-B1": {
    theme: "L'intégration en centre d'intervention et de secours",
    method: "",
    important: [],
    book: "",
  },
  "SC-B2": {
    theme: "La gestion du stress",
    method: "",
    important: [],
    book: "",
  },
  "APS-A1": {
    theme: "Les indicateurs de la condition physique",
    method: "",
    important: [],
    book: "",
  },
  "APS-A2": {
    theme: "La préparation physique aux épreuves du brevet de JSP",
    method: "",
    important: [],
    book: "",
  },
  M: {
    theme: "Manœuvres",
    method: "",
    important: [],
    book: "",
  },
};
